// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
//
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrQoFPv_mpSJnX-Jsb4BHhyDCfapg8uZ8',
    appId: '1:183873733971:web:d0ede755476cd51e9c8da6',
    messagingSenderId: '183873733971',
    projectId: 'test-1-68626',
    authDomain: 'test-1-68626.firebaseapp.com',
    storageBucket: 'test-1-68626.firebasestorage.app',
    measurementId: 'G-J0YPBLK9G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxZZBDmuY8v5dPj1RjZMhPI9CV0uOqszs',
    appId: '1:183873733971:android:1fa89fd3bded8ed89c8da6',
    messagingSenderId: '183873733971',
    projectId: 'test-1-68626',
    storageBucket: 'test-1-68626.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQxbyKqL7ZmD6MJ5aolS3rDHwmeLFjeoc',
    appId: '1:183873733971:ios:c9dbefe1a9b986dc9c8da6',
    messagingSenderId: '183873733971',
    projectId: 'test-1-68626',
    storageBucket: 'test-1-68626.firebasestorage.app',
    iosBundleId: 'com.example.demo3',
  );
}
